"use client";

import { useEffect, useMemo, useState } from "react";
import { PageHeader, Panel, PanelHeader, MetricCard, EmptyState } from "@/app/components/NexusPageKit";

type Summary={clicks:number;conversions:number;revenue:number;epc:number;cr:number;regs:number;deps:number};
type OfferRow={offerId:string;title:string;tag?:string|null;clicks:number;conversions:number;revenue:number;epc:number;cr:number;regs:number;deps:number};
type Series={day:string;clicks:number;conversions:number;revenue:number};
export default function StatsPage(){
 const [from,setFrom]=useState(()=>{const d=new Date();d.setDate(d.getDate()-7);return d.toISOString().slice(0,10)}); const [to,setTo]=useState(()=>new Date().toISOString().slice(0,10)); const [summary,setSummary]=useState<Summary|null>(null); const [offers,setOffers]=useState<OfferRow[]>([]); const [series,setSeries]=useState<Series[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;(async()=>{setLoading(true);const qs=new URLSearchParams({from:new Date(from+"T00:00:00Z").toISOString(),to:new Date(to+"T23:59:59Z").toISOString()});const [a,b,c]=await Promise.all([fetch(`/api/stats/summary?${qs}`,{cache:"no-store"}),fetch(`/api/stats/by-offer?${qs}`,{cache:"no-store"}),fetch(`/api/stats/timeseries?${qs}`,{cache:"no-store"})]);const [aj,bj,cj]=await Promise.all([a.json().catch(()=>null),b.json().catch(()=>null),c.json().catch(()=>null)]);if(!alive)return;setSummary(a.ok?aj:null);setOffers(b.ok&&Array.isArray(bj?.items)?bj.items:[]);setSeries(c.ok&&Array.isArray(cj?.series)?cj.series:[]);setLoading(false)})();return()=>{alive=false}},[from,to]);
 const s=summary??{clicks:0,conversions:0,revenue:0,epc:0,cr:0,regs:0,deps:0}; const regFtd=s.regs>0?s.deps/s.regs:0; const max=useMemo(()=>Math.max(1,...series.map(x=>Math.max(x.clicks,x.conversions))),[series]);
 return <div className="pb-10"><PageHeader eyebrow="Analytics" title="Statistics" subtitle="Live performance from clicks and conversions attributed to your account." actions={<div className="flex gap-2"><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="rounded-lg border border-white/[0.08] bg-[#101014] px-3 py-2 text-xs text-white/65"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="rounded-lg border border-white/[0.08] bg-[#101014] px-3 py-2 text-xs text-white/65"/></div>}/>
 <div className="space-y-5 p-5 md:p-8"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><MetricCard label="Revenue" value={money(s.revenue)} emphasis/><MetricCard label="Clicks" value={s.clicks.toLocaleString("en-US")}/><MetricCard label="Registrations" value={s.regs.toLocaleString("en-US")}/><MetricCard label="FTD / Deposits" value={s.deps.toLocaleString("en-US")}/><MetricCard label="Reg → FTD" value={`${(regFtd*100).toFixed(2)}%`}/><MetricCard label="EPC" value={money(s.epc)}/></div>
 <Panel><PanelHeader title="Performance" description="Daily live traffic for the selected period."/><div className="p-5">{loading?<div className="py-16 text-center text-xs text-white/35">Loading live metrics…</div>:series.length===0?<EmptyState title="No traffic in this period"/>:<div className="flex h-56 items-end gap-1">{series.map(x=><div key={x.day} className="group relative flex h-full min-w-0 flex-1 items-end"><div className="pointer-events-none absolute left-1/2 top-2 z-20 hidden w-44 -translate-x-1/2 rounded-lg border border-white/[0.10] bg-[#141419] p-3 text-[11px] shadow-2xl group-hover:block"><div className="mb-2 font-medium text-white/90">{x.day}</div><div className="space-y-1 text-white/55"><div className="flex justify-between gap-3"><span>Clicks</span><span className="text-white/90">{x.clicks}</span></div><div className="flex justify-between gap-3"><span>Conversions</span><span className="text-white/90">{x.conversions}</span></div><div className="flex justify-between gap-3"><span>Revenue</span><span className="text-white/90">{money(x.revenue)}</span></div></div></div><div className="w-full cursor-crosshair rounded-t-sm bg-[#7657ff]/55 transition group-hover:bg-[#7657ff]" style={{height:`${Math.max(3,(Math.max(x.clicks,x.conversions)/max)*100)}%`}}/></div>)}</div>}</div></Panel>
 <Panel><PanelHeader title="Performance by flow" description="Only NEXUS flows with attributed click activity are shown."/>{offers.length===0?<EmptyState title="No attributed offer activity"/>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="border-b border-white/[0.07] bg-black/10 text-[9px] uppercase tracking-[0.13em] text-white/28"><tr><th className="px-5 py-3">Flow</th><th>Clicks</th><th>REG</th><th>FTD</th><th>Conversions</th><th>Revenue</th><th>CR</th></tr></thead><tbody className="divide-y divide-white/[0.06]">{offers.map(r=><tr key={r.offerId} className="text-white/52 hover:bg-white/[0.02]"><td className="px-5 py-3"><div className="font-medium text-white/82">{r.title}</div><div className="mt-0.5 text-[10px] text-white/25">{r.tag??r.offerId}</div></td><td>{r.clicks}</td><td>{r.regs}</td><td>{r.deps}</td><td>{r.conversions}</td><td>{money(r.revenue)}</td><td>{(r.cr*100).toFixed(2)}%</td></tr>)}</tbody></table></div>}</Panel>
 </div></div>
}
function money(n:number){return `$${(Number(n)||0).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`}
