CREATE TYPE "Role" AS ENUM ('USER','ADMIN');
CREATE TYPE "UserStatus" AS ENUM ('PENDING','APPROVED','BANNED');

ALTER TABLE "User" ADD COLUMN "role" "Role" NOT NULL DEFAULT 'USER';
ALTER TABLE "User" ADD COLUMN "status" "UserStatus" NOT NULL DEFAULT 'PENDING';
ALTER TABLE "User" ADD COLUMN "telegram" TEXT;
ALTER TABLE "User" ADD COLUMN "passwordHash" TEXT;
ALTER TABLE "User" ADD COLUMN "image" TEXT;

CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
