import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { z } from "zod";
import { revalidatePath } from "next/cache";
import { EmptyState, MetricCard, PageHeader, Panel, PanelHeader, Pill } from "@/app/components/NexusPageKit";

const WalletSchema=z.object({address:z.string().min(8).max(200)});
function guessLabel(addr:string){const a=addr.trim();if(/^T[1-9A-HJ-NP-Za-km-z]{20,}$/.test(a))return"TRC20";if(/^0x[a-fA-F0-9]{40}$/.test(a))return"ERC20";if(/^(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,}$/i.test(a))return"BTC";return"CRYPTO"}
export default async function FinancePage({params:{locale}}:{params:{locale:string}}){const session=await auth();if(!session?.user)return null;const userId=(session.user as any).id as string;
 const [rev,paid,pending,wallets,payouts]=await Promise.all([prisma.conversion.aggregate({where:{userId,amount:{not:null}},_sum:{amount:true}}),prisma.payout.aggregate({where:{userId,status:"Paid"},_sum:{amount:true}}),prisma.payout.aggregate({where:{userId,status:"Pending"},_sum:{amount:true}}),prisma.wallet.findMany({where:{userId},orderBy:[{isPrimary:"desc"},{createdAt:"asc"}]}),prisma.payout.findMany({where:{userId},orderBy:{createdAt:"desc"}})]);
 const revenue=Number(rev._sum.amount??0),totalPaid=Number(paid._sum.amount??0),reserved=Number(pending._sum.amount??0),available=Math.max(0,revenue-totalPaid-reserved);
 async function addWallet(fd:FormData){"use server";const s=await auth();if(!s?.user)return;const parsed=WalletSchema.safeParse({address:String(fd.get("address")??"")});if(!parsed.success)return;const uid=(s.user as any).id as string;const address=parsed.data.address.trim();await prisma.$transaction(async tx=>{const count=await tx.wallet.count({where:{userId:uid}});await tx.wallet.create({data:{userId:uid,address,label:guessLabel(address),verified:false,isPrimary:count===0}})});revalidatePath(`/${locale}/finance`)}
 async function setPrimary(fd:FormData){"use server";const s=await auth();if(!s?.user)return;const uid=(s.user as any).id as string,id=String(fd.get("id")??"");if(!id)return;await prisma.$transaction([prisma.wallet.updateMany({where:{userId:uid},data:{isPrimary:false}}),prisma.wallet.updateMany({where:{id,userId:uid},data:{isPrimary:true}})]);revalidatePath(`/${locale}/finance`)}
 async function del(fd:FormData){"use server";const s=await auth();if(!s?.user)return;const uid=(s.user as any).id as string,id=String(fd.get("id")??"");if(!id)return;await prisma.wallet.deleteMany({where:{id,userId:uid}});const primary=await prisma.wallet.findFirst({where:{userId:uid,isPrimary:true}});if(!primary){const first=await prisma.wallet.findFirst({where:{userId:uid},orderBy:{createdAt:"asc"}});if(first)await prisma.wallet.update({where:{id:first.id},data:{isPrimary:true}})}revalidatePath(`/${locale}/finance`)}
 return <div className="pb-10"><PageHeader eyebrow="Finance" title="Finance" subtitle="Live balances, payout wallets and payout history. All amounts are derived from your database." />
 <div className="space-y-5 p-5 md:p-8"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Available balance" value={money(available)} hint="Revenue less paid and pending payouts" emphasis/><MetricCard label="Pending payouts" value={money(reserved)}/><MetricCard label="Total paid" value={money(totalPaid)}/><MetricCard label="Tracked revenue" value={money(revenue)}/></div>
 <Panel><PanelHeader title="Payout wallets" description="The first wallet becomes primary automatically." action={<form action={addWallet} className="flex gap-2"><input name="address" required placeholder="TRC20 / ERC20 / BTC address" className="h-9 w-64 rounded-lg border border-white/[0.08] bg-black/20 px-3 text-xs text-white outline-none placeholder:text-white/25"/><button className="rounded-lg bg-[#7657ff] px-3 text-xs font-semibold text-white">Add wallet</button></form>}/>{wallets.length===0?<EmptyState title="No payout wallets" description="Add a destination wallet before payout-request functionality is enabled."/>:<div className="divide-y divide-white/[0.06]">{wallets.map(w=><div key={w.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><span className="text-sm font-medium text-white/82">{w.label}</span>{w.isPrimary?<Pill tone="accent">Primary</Pill>:null}{w.verified?<Pill tone="success">Verified</Pill>:<Pill>Unverified</Pill>}</div><div className="mt-1 max-w-[680px] truncate font-mono text-[11px] text-white/32">{w.address}</div></div><div className="flex gap-2">{!w.isPrimary?<form action={setPrimary}><input type="hidden" name="id" value={w.id}/><button className="rounded-lg border border-white/[0.09] px-3 py-2 text-[11px] text-white/55">Set primary</button></form>:null}<form action={del}><input type="hidden" name="id" value={w.id}/><button className="rounded-lg border border-red-500/20 px-3 py-2 text-[11px] text-red-400/75">Delete</button></form></div></div>)}</div>}</Panel>
 <Panel><PanelHeader title="Payout history" description="Existing payout records from the live database."/>{payouts.length===0?<EmptyState title="No payouts yet"/>:<div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="border-b border-white/[0.07] bg-black/10 text-[9px] uppercase tracking-[0.13em] text-white/28"><tr><th className="px-5 py-3">Date</th><th>Amount</th><th>Status</th><th>Transaction</th></tr></thead><tbody className="divide-y divide-white/[0.06]">{payouts.map(p=><tr key={p.id} className="text-white/52"><td className="px-5 py-3">{p.createdAt.toISOString().slice(0,10)}</td><td>{money(Number(p.amount))} {p.currency}</td><td><Pill tone={p.status==="Paid"?"success":p.status==="Pending"?"warning":"default"}>{p.status}</Pill></td><td className="font-mono text-[11px]">{p.txHash??"—"}</td></tr>)}</tbody></table></div>}</Panel>
 </div></div>}
function money(n:number){return `$${n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`}
