"use client";

import { useEffect, useMemo, useState } from "react";
import { EmptyState, PageHeader, Panel, Pill } from "@/app/components/NexusPageKit";

type Offer = { id: string; title: string; tag?: string | null; geo: string; vertical: string; tier: number; cpa: number | null; cap?: number | null; minDeposit?: number | null; holdDays?: number | null; rules?: string | null; notes?: string | null; kpi1?: unknown; kpi2?: unknown; kpi1Text?: string | null; kpi2Text?: string | null; mode: "Auto" | "Manual"; };

export default function MyOffersPage() {
  const [rows, setRows] = useState<Offer[]>([]); const [loading, setLoading] = useState(true); const [q, setQ] = useState(""); const [expanded, setExpanded] = useState<string | null>(null); const [subIds, setSubIds] = useState<Record<string,string>>({}); const [links, setLinks] = useState<Record<string,string>>({}); const [busy, setBusy] = useState<string | null>(null);
  useEffect(() => { fetch("/api/offers/mine", { cache: "no-store" }).then(r=>r.json()).then(j=>setRows(Array.isArray(j?.items)?j.items:[])).finally(()=>setLoading(false)); }, []);
  const filtered = useMemo(() => rows.filter(r => `${r.title} ${r.geo} ${r.vertical} ${r.tag ?? ""}`.toLowerCase().includes(q.toLowerCase())), [rows,q]);
  async function buildLink(offerId:string){ setBusy(offerId); try { const res=await fetch("/api/offers/link",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({offerId,subId:subIds[offerId]||undefined})}); const j=await res.json(); if(!res.ok||!j?.link) return alert(j?.error??"Unable to build tracking link"); setLinks(p=>({...p,[offerId]:j.link})); } finally { setBusy(null); } }
  async function copy(id:string){ if(links[id]) await navigator.clipboard.writeText(links[id]); }
  return <div className="pb-10"><PageHeader eyebrow="Affiliate" title="My Offers" subtitle="Approved offers, commercial terms and live tracking-link generation." />
    <div className="space-y-5 p-5 md:p-8">
      <div className="grid gap-4 sm:grid-cols-3"><Stat label="Approved flows" value={rows.length}/><Stat label="Tracking ready" value={rows.filter(r=>!!r.id).length}/><Stat label="Catalog source" value="Live DB"/></div>
      <Panel className="p-4"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search approved offers" className="h-10 w-full rounded-lg border border-white/[0.08] bg-black/20 px-3 text-[13px] text-white outline-none placeholder:text-white/25 focus:border-[#7657ff]/40" /></Panel>
      {loading?<Panel><EmptyState title="Loading approved offers…"/></Panel>:filtered.length===0?<Panel><EmptyState title="No approved offers yet" description="Request access from Offers. Once approved by staff, the offer appears here automatically."/></Panel>:<div className="space-y-4">{filtered.map(r=><article key={r.id} className="rounded-xl border border-white/[0.08] bg-white/[0.025]">
        <button onClick={()=>setExpanded(expanded===r.id?null:r.id)} className="flex w-full items-center justify-between gap-4 p-5 text-left"><div><div className="flex flex-wrap items-center gap-2"><span className="text-[15px] font-semibold text-white">{r.title}</span><Pill tone="success">Approved</Pill><Pill>Tier {r.tier}</Pill></div><div className="mt-1.5 text-xs text-white/38">{r.geo} · {r.vertical}{r.tag?` · ${r.tag}`:""}</div></div><div className="text-xs text-[#8e79ff]">{expanded===r.id?"Hide details":"Open details"}</div></button>
        {expanded===r.id?<div className="border-t border-white/[0.07] p-5"><div className="grid gap-3 sm:grid-cols-4"><Mini label="CPA" value={r.cpa==null?"—":`$${r.cpa.toFixed(2)}`}/><Mini label="Cap" value={r.cap??"—"}/><Mini label="Min deposit" value={r.minDeposit==null?"—":`$${r.minDeposit.toFixed(2)}`}/><Mini label="Hold" value={r.holdDays==null?"—":`${r.holdDays}d`}/></div>
          <div className="mt-4 rounded-xl border border-[#7657ff]/20 bg-[#7657ff]/[0.045] p-4"><div className="text-[11px] font-semibold uppercase tracking-[0.14em] text-[#927cff]">Tracking link</div><div className="mt-3 grid gap-2 lg:grid-cols-[1fr_auto_auto]"><input value={subIds[r.id]??""} onChange={e=>setSubIds(p=>({...p,[r.id]:e.target.value}))} placeholder="sub_id (optional)" className="h-10 rounded-lg border border-white/[0.08] bg-black/25 px-3 text-xs text-white outline-none"/><button onClick={()=>buildLink(r.id)} disabled={busy===r.id} className="rounded-lg bg-[#7657ff] px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{busy===r.id?"Building…":"Build link"}</button><button onClick={()=>copy(r.id)} disabled={!links[r.id]} className="rounded-lg border border-white/[0.1] bg-white/[0.03] px-4 py-2 text-xs text-white/65 disabled:opacity-35">Copy</button></div>{links[r.id]?<div className="mt-3 break-all rounded-lg border border-white/[0.07] bg-black/20 p-3 font-mono text-[11px] text-white/55">{links[r.id]}</div>:null}</div>
          {(r.rules||r.notes)?<div className="mt-4 grid gap-3 md:grid-cols-2">{r.rules?<TextBlock title="Rules" text={r.rules}/>:null}{r.notes?<TextBlock title="Notes" text={r.notes}/>:null}</div>:null}
        </div>:null}
      </article>)}</div>}
    </div></div>;
}
function Stat({label,value}:{label:string;value:React.ReactNode}){return <div className="rounded-xl border border-white/[0.08] bg-white/[0.025] p-4"><div className="text-[10px] uppercase tracking-[0.14em] text-white/30">{label}</div><div className="mt-2 text-xl font-semibold text-white">{value}</div></div>}
function Mini({label,value}:{label:string;value:React.ReactNode}){return <div className="rounded-lg border border-white/[0.07] bg-black/15 p-3"><div className="text-[9px] uppercase tracking-[0.13em] text-white/30">{label}</div><div className="mt-1.5 text-[14px] font-semibold text-white/85">{value}</div></div>}
function TextBlock({title,text}:{title:string;text:string}){return <div className="rounded-lg border border-white/[0.07] bg-black/10 p-3"><div className="text-[9px] uppercase tracking-[0.13em] text-white/30">{title}</div><div className="mt-2 whitespace-pre-wrap text-xs leading-5 text-white/48">{text}</div></div>}
