"use client";
import { useEffect, useState, useTransition } from "react";
import { EmptyState, PageHeader, Panel, PanelHeader, Pill } from "@/app/components/NexusPageKit";
type Profile={id:string;email:string;name?:string|null;telegram?:string|null;image?:string|null;role:string;status:string;tier:number;assignedManager?:{name?:string|null;email:string;telegram?:string|null}|null;application?:{company?:string|null;trafficSources:string[];mainGeos:string[];verticalInterests:string[];experience?:string|null;estimatedMonthlyVolume?:string|null;about?:string|null}|null};
export default function ProfilePage(){const [p,setP]=useState<Profile|null>(null);const [name,setName]=useState("");const [telegram,setTelegram]=useState("");const [loading,setLoading]=useState(true);const [msg,setMsg]=useState<string|null>(null);const [pending,start]=useTransition();const [currentPassword,setCurrent]=useState("");const [newPassword,setNew]=useState("");const [repeat,setRepeat]=useState("");
 useEffect(()=>{fetch("/api/profile",{cache:"no-store"}).then(r=>r.json()).then(j=>{if(j?.user){setP(j.user);setName(j.user.name??"");setTelegram(j.user.telegram??"")}}).finally(()=>setLoading(false))},[]);
 function save(){start(async()=>{setMsg(null);const r=await fetch("/api/profile",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name,telegram})});if(!r.ok)return setMsg("Could not save profile");if(currentPassword||newPassword||repeat){if(newPassword!==repeat)return setMsg("New passwords do not match");const pr=await fetch("/api/profile/change-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({currentPassword,newPassword})});if(!pr.ok)return setMsg("Profile saved, but password change failed");setCurrent("");setNew("");setRepeat("")}setMsg("Changes saved");const j=await fetch("/api/profile",{cache:"no-store"}).then(x=>x.json());if(j?.user)setP(j.user)})}
 return <div className="pb-10"><PageHeader eyebrow="Account" title="Profile" subtitle="Account details, application traffic profile, assigned manager and security." actions={<button onClick={save} disabled={pending||loading} className="rounded-lg bg-[#7657ff] px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-50">{pending?"Saving…":"Save changes"}</button>}/><div className="space-y-5 p-5 md:p-8">{loading?<Panel><EmptyState title="Loading profile…"/></Panel>:!p?<Panel><EmptyState title="Profile unavailable"/></Panel>:<>
 <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><Panel><PanelHeader title="Account information"/><div className="grid gap-4 p-5 sm:grid-cols-2"><Field label="Full name"><input value={name} onChange={e=>setName(e.target.value)} className={input}/></Field><Field label="Telegram"><input value={telegram} onChange={e=>setTelegram(e.target.value)} className={input}/></Field><Field label="Email"><input value={p.email} readOnly className={`${input} text-white/35`}/></Field><Field label="Access"><div className="flex h-10 items-center gap-2"><Pill tone="success">{p.status}</Pill><Pill tone="accent">{p.role}</Pill>{p.role==="USER"?<Pill>Tier {p.tier}</Pill>:null}</div></Field></div></Panel>
 <Panel><PanelHeader title="Assigned manager" description="Your primary NEXUS contact."/><div className="p-5">{p.assignedManager?<><div className="text-sm font-semibold text-white/82">{p.assignedManager.name||"NEXUS Manager"}</div><div className="mt-1 text-xs text-white/38">{p.assignedManager.email}</div>{p.assignedManager.telegram?<div className="mt-3 inline-flex rounded-lg border border-white/[0.08] bg-white/[0.025] px-3 py-2 text-xs text-white/55">{p.assignedManager.telegram}</div>:null}</>:<EmptyState title="No manager assigned yet" description="Staff can assign a personal manager from the admin workspace."/>}</div></Panel></div>
 <Panel><PanelHeader title="Traffic profile" description="The information submitted with your affiliate application."/>{p.application?<div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-3"><Info label="Company / team" value={p.application.company}/><Info label="Main GEOs" value={p.application.mainGeos.join(", ")}/><Info label="Traffic sources" value={p.application.trafficSources.join(", ")}/><Info label="Vertical interests" value={p.application.verticalInterests.join(", ")}/><Info label="Experience" value={p.application.experience}/><Info label="Expected monthly volume" value={p.application.estimatedMonthlyVolume}/>{p.application.about?<div className="sm:col-span-2 xl:col-span-3"><Info label="About" value={p.application.about}/></div>:null}</div>:<EmptyState title="No application profile attached"/>}</Panel>
 <Panel><PanelHeader title="Security" description="Password management. Two-factor authentication will be wired during the security implementation stage."/><div className="grid gap-4 p-5 md:grid-cols-3"><Field label="Current password"><input type="password" value={currentPassword} onChange={e=>setCurrent(e.target.value)} className={input}/></Field><Field label="New password"><input type="password" value={newPassword} onChange={e=>setNew(e.target.value)} className={input}/></Field><Field label="Confirm new password"><input type="password" value={repeat} onChange={e=>setRepeat(e.target.value)} className={input}/></Field></div></Panel>{msg?<div className="rounded-xl border border-white/[0.08] bg-white/[0.025] px-4 py-3 text-xs text-white/60">{msg}</div>:null}</>}
 </div></div>}
const input="h-10 w-full rounded-lg border border-white/[0.08] bg-black/20 px-3 text-[13px] text-white outline-none focus:border-[#7657ff]/40";
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1.5 block text-[10px] font-semibold uppercase tracking-[0.12em] text-white/30">{label}</span>{children}</label>}
function Info({label,value}:{label:string;value?:string|null}){return <div className="rounded-lg border border-white/[0.07] bg-black/10 p-3"><div className="text-[9px] uppercase tracking-[0.13em] text-white/28">{label}</div><div className="mt-2 text-xs leading-5 text-white/55">{value||"—"}</div></div>}
